services:
#    museum_ticket.example:
#        class: Museum\TicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    museum.translation:
          class: Museum\TicketBundle\Services\TranslationService
          arguments: ["@doctrine.orm.entity_manager"]

    museum.isDateOfVisitOK:
        class: Museum\TicketBundle\Services\DateOfVisitService
        arguments: ["@doctrine.orm.entity_manager", "@museum.translation"]

    museum.priceFromBirthDate:
        class: Museum\TicketBundle\Services\PriceFromBirthDateService



    museum.visitorManagement:
      class: Museum\TicketBundle\Services\VisitorService
      arguments: ["@session"]

    Museum\TicketBundle\EventSubscriber\LocaleSubscriber:
        arguments: ["%kernel.default_locale%"]
        tags: [kernel.event_subscriber]
