services:
#    museum_ticket.example:
#        class: Museum\TicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    museum.isDateOfVisitOK:
        class: Museum\TicketBundle\Services\DateOfVisitService
        arguments: ["@doctrine.orm.entity_manager"]

    museum.priceFromBirthDate:
        class: Museum\TicketBundle\Services\PriceFromBirthDateService

    museum.visitorManagement:
      class: Museum\TicketBundle\Services\VisitorService
      arguments: ["@session"]

    museum.payment:
      class: Museum\TicketBundle\Services\TicketFolderPaymentService

    museum.dataPersistence:
      class: Museum\TicketBundle\Services\DataPersistenceService
      arguments: ["@doctrine.orm.entity_manager", "@session"]


    Museum\TicketBundle\EventSubscriber\LocaleSubscriber:
        arguments: ["%kernel.default_locale%"]
        tags: [kernel.event_subscriber]
